import React, { useState } from 'react';
import VideoInput from '../components/youtube/VideoInput';
import LessonList from '../components/youtube/LessonList';
import LessonContent from '../components/youtube/LessonContent';
import EmptyState from '../components/youtube/EmptyState';
import type { Lesson } from '../types/youtube';

const YouTubeLearning: React.FC = () => {
    const [videoUrl, setVideoUrl] = useState < string > ('');
    const [isProcessing, setIsProcessing] = useState < boolean > (false);
    const [selectedLesson, setSelectedLesson] = useState < Lesson | null > (null);
    const [lessons, setLessons] = useState < Lesson[] > ([
        // Mock data for now - will be replaced with backend integration
        {
            id: 1,
            video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            video_title: 'Introduction to React Hooks',
            thumbnail_url: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
            ai_summary: 'This video provides a comprehensive introduction to React Hooks, covering useState, useEffect, and custom hooks. It explains how hooks allow you to use state and other React features without writing a class component.',
            ai_notes: [
                'Hooks let you use state and other React features without writing a class',
                'useState is the most basic hook for managing component state',
                'useEffect handles side effects like data fetching and subscriptions',
                'Custom hooks let you extract component logic into reusable functions',
                'Rules of hooks: only call at the top level and only from React functions'
            ],
            quiz_questions: [
                {
                    question: 'What is the primary purpose of React Hooks?',
                    options: [
                        'To use state and lifecycle features in functional components',
                        'To replace all class components',
                        'To improve application performance',
                        'To handle routing'
                    ],
                    correct_answer: 'To use state and lifecycle features in functional components'
                },
                {
                    question: 'Which hook is used for managing component state?',
                    options: ['useEffect', 'useState', 'useContext', 'useReducer'],
                    correct_answer: 'useState'
                }
            ],
            flashcards: [
                {
                    front: 'What does useState return?',
                    back: 'An array with two elements: the current state value and a function to update it'
                },
                {
                    front: 'When does useEffect run?',
                    back: 'After every render by default, or when specified dependencies change'
                }
            ],
            category: 'Technology',
            duration_minutes: 15
        }
    ]);

    const extractVideoId = (url: string): string | null => {
        const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
        const match = url.match(regExp);
        return match && match[2].length === 11 ? match[2] : null;
    };

    const processVideo = async (): Promise<void> => {
        if (!videoUrl) return;

        setIsProcessing(true);
        try {
            const videoId = extractVideoId(videoUrl);
            if (!videoId) {
                alert('Invalid YouTube URL');
                return;
            }

            // TODO: Replace with actual backend API call
            // Simulating API call with setTimeout
            setTimeout(() => {
                const newLesson: Lesson = {
                    id: lessons.length + 1,
                    video_url: videoUrl,
                    video_title: 'New Video Lesson',
                    thumbnail_url: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
                    ai_summary: 'This is a placeholder summary. Backend integration will generate actual AI-powered summaries.',
                    ai_notes: [
                        'Key point 1 will be generated by AI',
                        'Key point 2 will be generated by AI',
                        'Key point 3 will be generated by AI'
                    ],
                    quiz_questions: [
                        {
                            question: 'Sample question?',
                            options: ['Option A', 'Option B', 'Option C', 'Option D'],
                            correct_answer: 'Option A'
                        }
                    ],
                    flashcards: [
                        {
                            front: 'Sample Question',
                            back: 'Sample Answer'
                        }
                    ],
                    category: 'General',
                    duration_minutes: 10
                };

                setLessons([newLesson, ...lessons]);
                setSelectedLesson(newLesson);
                setVideoUrl('');
                setIsProcessing(false);
            }, 2000);

            // When backend is ready, use this structure:
            /*
            const response = await fetch('/api/youtube/process', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ videoUrl })
            });
            
            const result: Lesson = await response.json();
            
            setLessons([result, ...lessons]);
            setSelectedLesson(result);
            setVideoUrl('');
            */
        } catch (error) {
            console.error('Error processing video:', error);
            alert('Error processing video. Please try again.');
            setIsProcessing(false);
        }
    };

    return (
        <div className="min-h-screen bg-[#0F0F23] p-6">
            <div className="max-w-7xl mx-auto">
                <div className="mb-8">
                    <h1 className="text-4xl font-bold text-white mb-2">YouTube Learning</h1>
                    <p className="text-gray-400">
                        Transform any YouTube video into structured learning content
                    </p>
                </div>

                <VideoInput
                    videoUrl={videoUrl}
                    setVideoUrl={setVideoUrl}
                    onProcess={processVideo}
                    isProcessing={isProcessing}
                />

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    <LessonList
                        lessons={lessons}
                        selectedLesson={selectedLesson}
                        onSelectLesson={setSelectedLesson}
                    />

                    <div className="lg:col-span-2">
                        {selectedLesson ? (
                            <LessonContent
                                lesson={selectedLesson}
                                extractVideoId={extractVideoId}
                            />
                        ) : (
                            <EmptyState />
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default YouTubeLearning;